version: '3'

services:
  spark-master:
    image: fuljo/spark-base:3-java8
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    volumes:
      - events:/tmp/spark-events
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker:
    image: fuljo/spark-base:3-java8
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/opt/spark/work/data
      - ./results:/opt/spark/work/results
      - events:/tmp/spark-events
  spark-history:
    image: fuljo/spark-base:3-java8
    depends_on:
      - spark-master
      - spark-worker
    environment:
      - SPARK_MODE=history-server
      - SPARK_EVENTLOG_ENABLED=1
    volumes:
      - events:/tmp/spark-events
    ports:
      - "18080:18080"
  spark-driver:
    build: .
    image: fuljo/mask-the-week
    depends_on:
      - spark-master
      - spark-worker
    environment:
      - APP_ARGS=/opt/spark/work/data/data.csv /opt/spark/work/results
      - SPARK_EVENTLOG_ENABLED=1
    volumes:
      - ./data:/opt/spark/work/data
      - ./results:/opt/spark/work/results
      - events:/tmp/spark-events
volumes:
  events: {}